export const NAVBAR_ICON_SIZE = 3;
export const NAVBAR_PADDING = 1;
export const NAVBAR_MIN_WIDTH = NAVBAR_ICON_SIZE + NAVBAR_PADDING;
export const HEADER_HEIGHT = 10
export const CONTENT_HEIGHT = 100 - HEADER_HEIGHT;